#!/bin/sh

test -f /usr/bin/git || exit 0

. /lib/lsb/init-functions

GITDAEMON_OPTIONS="daemon --reuseaddr --verbose --base-path=/opt/git/ --detach --export-all --enable=receive-pack"

case "$1" in
start)  log_daemon_msg "Starting git-daemon"

        start-stop-daemon --start -c root:root --quiet --background \
                     --exec /usr/bin/git -- ${GITDAEMON_OPTIONS}

        log_end_msg $?
        ;;
stop)   log_daemon_msg "Stopping git-daemon"

        start-stop-daemon --stop --quiet --name git-daemon

        log_end_msg $?
        ;;
*)      log_action_msg "Usage: /etc/init.d/git-service {start|stop}"
        exit 2
        ;;
esac
exit 0